name: segmentation_tool_env
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - bzip2
  - ca-certificates
  - giflib
  - glib
  - glib-tools
  - icu
  - jpeg
  - krb5
  - lerc
  - libclang
  - libclang13
  - libdeflate
  - libffi
  - libglib
  - libiconv
  - libpng
  - libpq
  - libtiff
  - libwebp
  - libwebp-base
  - libxml2
  - libxslt
  - lz4-c
  - openssl
  - pcre2
  - pip
  - ply
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - python=3.7
  - qt-main
  - qt-webengine
  - qtwebkit
  - setuptools
  - sip=6.6.2
  - sqlite
  - toml
  - wheel
  - xz
  - zlib
  - zstd
  - pip:
      - certifi==2024.12.14
      - charset-normalizer==3.4.1
      - colorama==0.4.6
      - cycler==0.11.0
      - decorator==5.1.1
      - edflib-python==1.0.8
      - idna==3.10
      - jinja2==3.1.5
      - kiwisolver==1.4.5
      - markupsafe==2.1.5
      - matplotlib==3.1.1
      - mne==1.3.1
      - numpy==1.21.6
      - packaging==24.0
      - platformdirs==4.0.0
      - pooch==1.8.2
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - requests==2.31.0
      - scipy==1.7.3
      - six==1.17.0
      - tqdm==4.67.1
      - typing-extensions==4.7.1
      - urllib3==2.0.7

